/* Generate `sections/index.generated.ts` — the smoke list, discovered.
 *
 * esbuild (and tsc) need STATIC imports, so the list of sections has to exist as
 * source. What must never exist is a HAND-EDITED list: that is the appendix this
 * whole shape replaced, one line long instead of 2.300, and two cards appending
 * to it still conflict. So it is generated, in SLUG order — deterministic,
 * so the run order is stable and no section "goes first" by merge accident — and
 * gitignored, so it is never committed and never mergeable.
 *
 * TWO FILES, ONE SLUG IS REFUSED LOUDLY. `foo.ts` beside `foo.tsx` is the §9 bug
 * reborn — two workers naming one concept — and it is exactly the case a
 * filesystem does not catch for you. It stops the build here, by name.
 *
 * Called by `run.mjs` before it builds, and by `npm run typecheck` before tsc,
 * because both read the generated file.
 *
 *     node smoke/sections.mjs [dir]     # default: smoke/sections/
 *
 * The directory is a parameter for ONE reason: `tests/test_ui.py` runs this over
 * a throwaway git repo where two branches each added a section, which is the
 * property this whole shape exists to buy and is therefore tested as such.
 */
import { readdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const HERE = new URL("./sections/", import.meta.url);

/** The order, as a PURE function of the names — separate from the `readdir` on
 *  purpose, so it is pinned by a test and not by whatever order a filesystem
 *  happens to hand back (APFS returns names sorted; ext4 returns hash order, and
 *  a run order that changes with the filesystem is not a run order).
 *
 *  It sorts by SLUG and not by filename, and the difference is not cosmetic:
 *  `-` (0x2d) sorts BEFORE `.` (0x2e), so `actors-window-filter.tsx` lands ahead
 *  of `actors.tsx` while the slugs read the other way round. A slug that is the
 *  prefix of another is the normal way a page and its detail get named, so
 *  filename order would have made the index disagree with its own list of names
 *  the first time somebody did it. The slug is the identity everywhere else
 *  here — the import path, the index key, the duplicate check below — so it is
 *  the identity the order is over too. */
export function order(names) {
  return names
    .filter((n) => /\.tsx?$/.test(n))
    .filter((n) => n !== "section.ts" && n !== "index.generated.ts")
    .sort((a, b) => (slugOf(a) < slugOf(b) ? -1 : slugOf(a) > slugOf(b) ? 1 : 0));
}

/** The name a section is known by: the file, without its extension. */
export function slugOf(name) {
  return name.replace(/\.tsx?$/, "");
}

/** Every section file, by slug, in slug order. `section.ts` is the seam, not
 *  a section; the generated index is not a section either. */
export async function discover(dir = HERE) {
  const names = order(await readdir(fileURLToPath(dir)));

  const bySlug = new Map();
  for (const name of names) {
    const slug = slugOf(name);
    const seen = bySlug.get(slug);
    if (seen !== undefined) {
      throw new Error(
        `smoke/sections: two files claim the slug "${slug}" — ${seen} and ${name}. ` +
          "One slug is one section; rename one after what it actually pins.",
      );
    }
    bySlug.set(slug, name);
  }
  return [...bySlug].map(([slug, name]) => ({ slug, name }));
}

export async function generate(dir = HERE) {
  const found = await discover(dir);
  const body = [
    "/* GENERATED by smoke/sections.mjs — do not edit, do not commit.",
    " * The list of smoke sections, in slug order. */",
    'import type { Section } from "./section";',
    "",
    ...found.map((s, i) => `import { run as s${i} } from "./${s.slug}";`),
    "",
    "export const SECTIONS: [string, Section][] = [",
    ...found.map((s, i) => `  [${JSON.stringify(s.slug)}, s${i}],`),
    "];",
    "",
  ].join("\n");
  await writeFile(new URL("index.generated.ts", dir), body, "utf-8");
  return found;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const where = process.argv[2]
    ? new URL(`${process.argv[2].replace(/\/?$/, "/")}`, `file://${process.cwd()}/`)
    : HERE;
  const found = await generate(where);
  console.log(`smoke/sections: ${found.length} section(s)`);
}
