"""The registry of specialist agents, and the two decisions a board can make with it.

taskops never invokes an agent. It knows WHICH agent a card belongs to (`agent_for`) and it
refuses a claim from an agent the card does not belong to (`fenced`) — the host session does
the spawning, with its own sub-agent tool. That split is not a limitation to work around: a
board that spawned processes would be a second, invisible fleet nobody asked for.

Two directories, ONE parser:

```
plugin/agents/*.md      the DEFAULTS  — manager, worker, verifier, shipped with taskops
.taskops/agents/*.md    the SPECIALISTS — committed, travelling through git with the project
```

A repo file with the same `name` as a plugin file WINS, because a project must be able to
override the stock worker without forking the plugin.

A malformed file is a WARNING and a skip, never an exception: agent files are edited by hand,
and a typo in one of them must not be able to stop a session from starting.
"""

from __future__ import annotations

import re
import warnings
from pathlib import Path

from .._errors import BadRequest, TaskopsError
from ..contracts.agents import AgentSpec
from ._agentfile import parse_agent, without_keys

__all__ = ["REGISTRY_DIR", "MARKER", "OURS", "registry", "specialists", "agent_for",
           "agent_named", "fenced", "materialised"]

REGISTRY_DIR = ".taskops/agents"

MARKER = "# generated by taskops from"
"""The line that says a file in `.claude/agents/` is ours to overwrite and ours to prune.
Anything without it was written by a human and is never touched — see `hooks._materialise`."""

OURS = ("labels", "files")
"""The taskops-only keys. Stripped from the materialised copy: Claude Code does not know
them, and a frontmatter key it does not know is noise in somebody else's file format."""


def specialists(root: Path | str) -> list[AgentSpec]:
    """The project's own agents, by name. Empty when `.taskops/agents/` is absent — which is
    the regression guard for every project that predates this: no registry, no behaviour."""
    return _load(Path(root) / REGISTRY_DIR)


def registry(root: Path | str) -> list[AgentSpec]:
    """Defaults plus specialists, the repo overriding the plugin by `name`."""
    merged = {spec["name"]: spec for spec in _load(_plugin_dir())}
    merged.update({spec["name"]: spec for spec in specialists(root)})
    return [merged[name] for name in sorted(merged)]


def agent_for(root: Path | str, labels: list[str]) -> str:
    """The specialist a card belongs to, or "" for none.

    Most shared labels wins; a tie goes to the alphabetically first name. Deterministic on
    purpose — a router that picked differently on two runs would make a fleet unreproducible,
    and "which agent got this card" is the first question anybody asks when one goes wrong.
    """
    wanted = set(labels)
    scored = [(-len(wanted & set(a["labels"])), a["name"]) for a in registry(root) if a["labels"]]
    ranked = sorted(score for score in scored if score[0] < 0)
    return ranked[0][1] if ranked else ""


def agent_named(root: Path | str, actor: str) -> AgentSpec | None:
    """The registry entry an actor id names, or None.

    `agent:<dev>/<name>` — the tail is the registry key. An actor that matches nothing stays
    UNRESTRICTED: a human's ad-hoc worker must not become fenced in just because specialists
    exist, or adding one agent would quietly change the rules for everybody else.
    """
    tail = actor.rsplit("/", 1)[-1]
    return next((a for a in registry(root) if a["name"] == tail), None)


def fenced(agent: AgentSpec | None, labels: list[str]) -> str:
    """Why this agent may not have this card, or "" if it may.

    Names BOTH label sets, because the useful refusal is not "no" but "you do X, this is Y".
    """
    if agent is None or not agent["labels"]:
        return ""
    if set(labels) & set(agent["labels"]):
        return ""
    theirs = ", ".join(labels) or "no labels"
    return (f"{agent['name']} works on [{', '.join(agent['labels'])}]; this card carries "
            f"[{theirs}] — it belongs to another specialist")


def materialised(spec: AgentSpec) -> str:
    """The file to write into `.claude/agents/`: the original, minus our keys, plus the marker,
    with the taskops tool names spelled the way the HOST resolves them.

    That last translation is not cosmetic. Claude Code namespaces MCP tools as
    `mcp__<server>__<tool>`, and a `tools:` entry it cannot resolve is dropped in SILENCE — so a
    registry saying `taskops_next` produced a specialist with Read, Edit and Bash and no way to
    claim anything. It was spawned, it read the card, and it could not take it. Writing
    `mcp__taskops__taskops_next` in the registry would work too, but the registry is a project
    document people edit by hand and the short name is the one they know.
    """
    lines = without_keys(_qualified(spec["text"]), OURS).splitlines()
    close = next((i for i in range(1, len(lines)) if lines[i].strip() == "---"), 0)
    marker = f"{MARKER} {REGISTRY_DIR}/{spec['name']}.md"
    return "\n".join([*lines[:close + 1], "", marker, *lines[close + 1:]]) + "\n"


def _qualified(text: str) -> str:
    """`taskops_next` -> `mcp__taskops__taskops_next`, only on a `tools:` line, only for names
    we own, and only when they are not already qualified."""
    out: list[str] = []
    for line in text.splitlines():
        if line.startswith("tools:"):
            line = re.sub(r"(?<!__)\b(taskops_[a-z_]+)", r"mcp__taskops__\1", line)
        out.append(line)
    return "\n".join(out) + ("\n" if text.endswith("\n") else "")


def _plugin_dir() -> Path:
    """Shipped next to the source in a checkout; absent from an installed wheel, which is fine
    — the defaults are then whatever the installed plugin already gave Claude Code."""
    return Path(__file__).resolve().parents[3] / "plugin" / "agents"


def _load(folder: Path) -> list[AgentSpec]:
    out: list[AgentSpec] = []
    if not folder.is_dir():
        return out
    for path in sorted(folder.glob("*.md")):
        try:
            out.append(parse_agent(path.read_text(encoding="utf-8"), path))
        except (BadRequest, TaskopsError, OSError, UnicodeDecodeError) as err:
            warnings.warn(f"taskops: skipping agent file — {err}", stacklevel=2)
    return out
