"""The outbound mirror's last word — one row per board, in live.sqlite.

§16 ("The host becomes the remote") made the declared forge an OUTBOUND
mirror: a push that lands on `repo.git` is pushed onward, best effort. Best
effort is only honest if it is LEGIBLE, so the result of that leg is a fact a
reader can see — and this module is the one place it is kept.

**Why live.sqlite and not the event log.** The log is the board's truth and it
TRAVELS (`board push`/`board pull` move it between machines, `verbs/record.py`
folds it anywhere). Whether one host's filesystem could reach GitHub ten
seconds ago is not a fact about the board: replayed on another machine it
would be a lie, and `gitwork/remote.py::push` already argues the general form
("a push is not a board fact, and half-recorded infrastructure state is
drift"). It belongs exactly where leases and presence belong — beside the
process that observed it, disposable, regenerated by the next push.

**Why not a log line only.** A log line is invisible to every reader the
board has: the orchestrator reads `taskops_board`, the human reads the window.
An invisible best-effort is how a forge quietly drifts a month behind, which
is the failure this module exists to prevent, so the fact rides on the board
PAYLOAD (`verbs/pulse.py`, beside `forge`, rendered by `mcp/boardview.py`)
under the same contract `forge` has: nothing to say sends NO KEY, never a
`null`, so a reader that never heard of the outbound leg sees the payload it
always saw.

**One row per forge LABEL, and the newest observation wins.** Keying on the
label rather than on a constant means re-declaring the forge resets the report
instead of inheriting a stranger's failure — a board pointed at a new repo has
said nothing yet about it, which is true. And the upsert is guarded by `at`:
two pushes race by construction (`gitwork/onward.py` argues that a whole-refs
push means the later subsumes the earlier), and their threads may finish out
of order, so an older failure must not be allowed to overwrite a newer
success.
"""

from __future__ import annotations

import sqlite3
from typing import Any

from .live import Live
from ..core import forge as forges
from .._errors import TaskopsError

__all__ = ["DETAIL_LIMIT", "record", "last", "glance"]

DETAIL_LIMIT = 600
"""How much of the complaint is kept. It rides on every board read, so it is
bounded here rather than at the reader; the first lines of a push failure are
the ones that name the cause ("Permission denied (publickey)", "non-fast-
forward"), and the host's own log keeps whatever this cut off. It is not
tighter than this because the one sentence that is OURS ends in a filesystem
path and the command that fixes it (`gitwork/onward.py::NO_REMOTE`) — a cap
that cut the fix off the end of the instruction would be the silent failure
this whole module exists to prevent."""


def record(live: Live, forge: str, *, ok: bool, detail: str, at: float) -> None:
    """Write what the outbound leg just did. The newest observation wins."""
    try:
        with live.db:
            live.db.execute(
                "INSERT INTO mirror (forge, ok, at, detail) VALUES (?, ?, ?, ?)"
                " ON CONFLICT(forge) DO UPDATE SET"
                " ok = excluded.ok, at = excluded.at, detail = excluded.detail"
                " WHERE excluded.at >= mirror.at",
                (forge, 1 if ok else 0, at, detail[:DETAIL_LIMIT]),
            )
    except sqlite3.Error as err:
        raise TaskopsError(f"live store: cannot record the mirror push: {err}") from err


def last(live: Live, forge: str) -> dict[str, Any] | None:
    """`{forge, ok, at, detail}` for that forge, or None if it has said nothing."""
    try:
        rows = live.db.execute(
            "SELECT ok, at, detail FROM mirror WHERE forge = ?", (forge,)
        ).fetchall()
    except sqlite3.Error as err:
        raise TaskopsError(f"live store: {err}") from err
    if not rows:
        return None
    ok, at, detail = rows[0]
    return {"forge": forge, "ok": bool(ok), "at": float(at), "detail": str(detail)}


def glance(live: Live, fact: object) -> dict[str, Any]:
    """The board payload's `mirror` fragment — `{}` when there is nothing true
    to say, which is a board with no declared forge and a board whose first
    push has not landed yet. Splatted by the caller for `forge`'s reason: an
    absent key is one thing a consumer must know about, `null` is two."""
    said = forges.understood(fact)
    if said is None:
        return {}
    seen = last(live, forges.label(said))
    return {"mirror": seen} if seen else {}
